# version: "3.8"

# services:
#   # Redis service for Celery broker
#   redis:
#     image: redis:alpine
#     ports:
#       - "6380:6379" # Corrected port mapping
#     networks:
#       - backend

#   # PostgreSQL database service
#   db:
#     image: postgres:13
#     environment:
#       - POSTGRES_DB=${DB_NAME}
#       - POSTGRES_USER=${DB_USER}
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - backend

#   # Django application service
#   web:
#     build: .
#     command: bash -c "sleep 5 && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#     volumes:
#       - .:/app
#       - static_volume:/app/staticfiles
#       - media_volume:/app/media
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - db
#       - redis
#     networks:
#       - backend

#   # Celery worker service for background tasks
#   celery_worker:
#     build: .
#     command: celery -A flightops worker --loglevel=info
#     volumes:
#       - .:/app
#     depends_on:
#       - db
#       - redis
#     env_file:
#       - .env

#     environment:
#       - DJANGO_SETTINGS_MODULE=flightops.settings

#     networks:
#       - backend

#   # Celery beat service for periodic tasks
#   celery_beat:
#     build: .
#     command: celery -A flightops beat --loglevel=info
#     volumes:
#       - .:/app
#     depends_on:
#       - db
#       - redis
#     env_file:
#       - .env

#     environment:
#       - DJANGO_SETTINGS_MODULE=flightops.settings
#     networks:
#       - backend

# volumes:
#   postgres_data:
#   static_volume:
#   media_volume:

# networks:
#   backend:
#     driver: bridge

version: "3.8"

services:
  # Redis service for Celery broker
  redis:
    image: redis:alpine
    ports:
      - "6380:6379" # Expose Redis on port 6380 for external use
    networks:
      - backend

  # PostgreSQL database service
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # Django application service
  web:
    build: . # Builds the Dockerfile in the current directory
    command: bash -c "sleep 5 && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app # Mounts the current directory as /app in the container
      - static_volume:/app/staticfiles # Persistent volume for static files
      - media_volume:/app/media # Persistent volume for media files
    ports:
      - "8000:8000" # Exposes the Django app on port 8000
    env_file:
      - .env # Environment variables (database creds, etc.)
    depends_on:
      - db
      - redis # This makes sure the Redis and DB services are up before starting the web service
    networks:
      - backend

  # Celery worker service for background tasks
  celery_worker:
    build: .
    command: celery -A flightops worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=flightops.settings
    networks:
      - backend

  # Celery beat service for periodic tasks
  celery_beat:
    build: .
    command: celery -A flightops beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=flightops.settings
    networks:
      - backend

  # Nginx service (reverse proxy for Django app)
  nginx:
    image: nginx:latest # Use the official Nginx image
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your Nginx config
      - ./server.crt:/etc/nginx/ssl/server.crt:ro # Mount your SSL certificate
      - ./server.key:/etc/nginx/ssl/server.key:ro # Mount your SSL key
      - ./static_volume:/var/www/staticfiles # Mount static files
      - ./media_volume:/var/www/media # Mount media files
    ports:
      - "80:80" # Expose HTTP port
      - "443:443" # Expose HTTPS port
    depends_on:
      - web # Ensure the Django app is up before starting Nginx
    networks:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend:
    driver: bridge
