# Generated by Django 5.0.9 on 2024-10-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcarsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=6)),
                ('origin_icao', models.CharField(max_length=10)),
                ('origin_iata', models.CharField(blank=True, max_length=10, null=True)),
                ('destination_icao', models.CharField(max_length=10)),
                ('destination_iata', models.CharField(blank=True, max_length=10, null=True)),
                ('atd_utc', models.TimeField(blank=True, null=True)),
                ('takeoff_utc', models.TimeField(blank=True, null=True)),
                ('touchdown_utc', models.TimeField(blank=True, null=True)),
                ('ata_utc', models.TimeField(blank=True, null=True)),
                ('raw_message', models.TextField()),
            ],
            options={
                'db_table': 'acars_message',
            },
        ),
        migrations.CreateModel(
            name='AirportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=10, unique=True)),
                ('icao_code', models.CharField(blank=True, max_length=10, null=True)),
                ('airport_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'airport_data',
            },
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=6)),
                ('tail_no', models.CharField(blank=True, max_length=10, null=True)),
                ('dep_code_iata', models.CharField(max_length=10)),
                ('dep_code_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('arr_code_iata', models.CharField(max_length=10)),
                ('arr_code_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('scheduled_departure_date_utc', models.DateField()),
                ('scheduled_arrival_date_utc', models.DateField(blank=True, null=True)),
                ('std_utc', models.TimeField(blank=True, null=True)),
                ('atd_utc', models.TimeField(blank=True, null=True)),
                ('takeoff_utc', models.TimeField(blank=True, null=True)),
                ('touchdown_utc', models.TimeField(blank=True, null=True)),
                ('ata_utc', models.TimeField(blank=True, null=True)),
                ('sta_utc', models.TimeField(blank=True, null=True)),
                ('source_type', models.CharField(max_length=20)),
                ('raw_content', models.TextField()),
            ],
            options={
                'db_table': 'flight_data',
            },
        ),
    ]
