# Generated by Django 5.0.9 on 2025-02-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='crew_id',
            field=models.CharField(max_length=10),
        ),
    ]
