# Generated by Django 5.0.9 on 2024-10-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightdata',
            old_name='scheduled_arrival_date_utc',
            new_name='sa_date_utc',
        ),
        migrations.RenameField(
            model_name='flightdata',
            old_name='scheduled_departure_date_utc',
            new_name='sd_date_utc',
        ),
    ]
