# Generated by Django 5.0.9 on 2025-02-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0002_alter_crewmember_crew_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crewmember',
            unique_together={('flight_no', 'sd_date_utc', 'crew_id')},
        ),
    ]
