# Generated by Django 5.0.9 on 2024-11-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0002_rename_scheduled_arrival_date_utc_flightdata_sa_date_utc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdata',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
