# Generated by Django 5.0.9 on 2025-02-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0003_alter_crewmember_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crewmember',
            name='crew_member_flight__1090e8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='crewmember',
            unique_together=set(),
        ),
    ]
