# Generated by Django 5.0.9 on 2024-11-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0003_flightdata_is_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdata',
            name='is_updated',
        ),
    ]
