# Generated by Django 5.0.9 on 2025-01-14 09:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0004_remove_flightdata_is_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'airport_destinations',
            },
        ),
        migrations.CreateModel(
            name='CargoFlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=6)),
                ('tail_no', models.CharField(blank=True, max_length=10, null=True)),
                ('dep_code_iata', models.CharField(max_length=10)),
                ('dep_code_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('arr_code_iata', models.CharField(max_length=10)),
                ('arr_code_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('sd_date_utc', models.DateField()),
                ('sa_date_utc', models.DateField(blank=True, null=True)),
                ('std_utc', models.TimeField(blank=True, null=True)),
                ('atd_utc', models.TimeField(blank=True, null=True)),
                ('takeoff_utc', models.TimeField(blank=True, null=True)),
                ('touchdown_utc', models.TimeField(blank=True, null=True)),
                ('ata_utc', models.TimeField(blank=True, null=True)),
                ('sta_utc', models.TimeField(blank=True, null=True)),
                ('source_type', models.CharField(max_length=20)),
                ('raw_content', models.TextField()),
            ],
            options={
                'db_table': 'cargo_flight_data',
            },
        ),
        migrations.CreateModel(
            name='CrewOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'crew_info',
            },
        ),
        migrations.CreateModel(
            name='FdmFlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=6)),
                ('tail_no', models.CharField(blank=True, max_length=10, null=True)),
                ('dep_code_iata', models.CharField(max_length=10)),
                ('dep_code_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('arr_code_iata', models.CharField(max_length=10)),
                ('arr_code_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('sd_date_utc', models.DateField()),
                ('sa_date_utc', models.DateField(blank=True, null=True)),
                ('std_utc', models.TimeField(blank=True, null=True)),
                ('atd_utc', models.TimeField(blank=True, null=True)),
                ('takeoff_utc', models.TimeField(blank=True, null=True)),
                ('touchdown_utc', models.TimeField(blank=True, null=True)),
                ('ata_utc', models.TimeField(blank=True, null=True)),
                ('sta_utc', models.TimeField(blank=True, null=True)),
                ('flight_type', models.CharField(max_length=20)),
                ('etd_utc', models.TimeField(blank=True, null=True)),
                ('eta_utc', models.TimeField(blank=True, null=True)),
                ('source_type', models.CharField(max_length=20)),
                ('raw_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fdm_flight_data',
            },
        ),
        migrations.CreateModel(
            name='CompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('time_in_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'completion_record',
                'indexes': [models.Index(fields=['employee_id', 'course_code', 'completion_date'], name='completion__employe_6bf5d4_idx')],
                'unique_together': {('employee_id', 'course_code', 'completion_date')},
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=6)),
                ('sd_date_utc', models.DateField()),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('crew_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('CP', 'Captain'), ('FO', 'First Officer'), ('FP', 'Purser'), ('SA', 'Senior Attendant'), ('FA', 'Flight Attendant'), ('FE', 'Flight Engineer'), ('AC', 'Air Crew')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crew_member',
                'indexes': [models.Index(fields=['flight_no', 'crew_id'], name='crew_member_flight__1090e8_idx')],
                'unique_together': {('flight_no', 'crew_id')},
            },
        ),
        migrations.CreateModel(
            name='DutyOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField()),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('layover_time_minutes', models.PositiveIntegerField(default=0)),
                ('tail_number', models.CharField(blank=True, max_length=20)),
                ('arrival_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_arrivals', to='aimsintegration.airportold')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimsintegration.crewold')),
                ('departure_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_departures', to='aimsintegration.airportold')),
            ],
            options={
                'db_table': 'duty_info',
            },
        ),
        migrations.CreateModel(
            name='InvoiceOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimsintegration.crewold')),
            ],
            options={
                'db_table': 'crew_invoice',
                'unique_together': {('crew', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TableauData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_day', models.DateField()),
                ('departure_station', models.CharField(max_length=25)),
                ('flight_no', models.CharField(max_length=25)),
                ('flight_leg_code', models.CharField(max_length=25)),
                ('cancelled_deleted', models.BooleanField(default=0)),
                ('arrival_station', models.CharField(max_length=25)),
                ('aircraft_reg_id', models.CharField(blank=True, max_length=25, null=True)),
                ('aircraft_type_index', models.CharField(blank=True, max_length=25, null=True)),
                ('aircraft_category', models.CharField(blank=True, max_length=25, null=True)),
                ('flight_service_type', models.CharField(blank=True, max_length=25, null=True)),
                ('std', models.TimeField(blank=True, null=True)),
                ('sta', models.TimeField(blank=True, null=True)),
                ('original_operation_day', models.DateField(blank=True, null=True)),
                ('original_std', models.TimeField(blank=True, null=True)),
                ('original_sta', models.TimeField(blank=True, null=True)),
                ('departure_delay_time', models.IntegerField(blank=True, null=True)),
                ('delay_code_kind', models.CharField(blank=True, max_length=25, null=True)),
                ('delay_number', models.CharField(blank=True, max_length=25, null=True)),
                ('aircraft_config', models.CharField(blank=True, max_length=25, null=True)),
                ('seat_type_config', models.CharField(blank=True, max_length=25, null=True)),
                ('atd', models.TimeField(blank=True, null=True)),
                ('takeoff', models.TimeField(blank=True, null=True)),
                ('touchdown', models.TimeField(blank=True, null=True)),
                ('ata', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tableau_data',
                'indexes': [models.Index(fields=['updated_at'], name='tableau_dat_updated_7521b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimsintegration.dutyold')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimsintegration.invoiceold')),
            ],
            options={
                'db_table': 'invoice_item',
                'unique_together': {('invoice', 'duty')},
            },
        ),
    ]
