# Generated by Django 5.0.9 on 2025-02-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0004_remove_crewmember_crew_member_flight__1090e8_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crewmember',
            unique_together={('flight_no', 'sd_date_utc', 'origin', 'destination', 'crew_id')},
        ),
        migrations.AddIndex(
            model_name='crewmember',
            index=models.Index(fields=['flight_no', 'crew_id'], name='crew_member_flight__1090e8_idx'),
        ),
    ]
