# Generated by Django 5.0.9 on 2025-01-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0005_airport_cargoflightdata_crew_fdmflightdata_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('crew', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'duty')},
        ),
        migrations.AlterModelTable(
            name='airport',
            table='destinations',
        ),
        migrations.AlterModelTable(
            name='crew',
            table='crew_info',
        ),
        migrations.AlterModelTable(
            name='duty',
            table='duty_info',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='crew_invoice',
        ),
        migrations.AlterModelTable(
            name='invoiceitem',
            table='invoice_item',
        ),
    ]
