# Generated by Django 5.0.9 on 2025-01-17 23:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0006_zone_airport_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'crew_info_old',
            },
        ),
        migrations.CreateModel(
            name='ZoneOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'db_table': 'zone_info_old',
            },
        ),
        migrations.CreateModel(
            name='AirportOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=10, unique=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airports_old', to='aimsintegration.zone')),
            ],
            options={
                'db_table': 'airport_destinations_old',
            },
        ),
        migrations.CreateModel(
            name='DutyOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField()),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('layover_time_minutes', models.PositiveIntegerField(default=0)),
                ('tail_number', models.CharField(blank=True, max_length=20)),
                ('arrival_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_arrivals_old', to='aimsintegration.airport')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimsintegration.crew')),
                ('departure_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_departures_old', to='aimsintegration.airport')),
            ],
            options={
                'db_table': 'duty_info_old',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimsintegration.duty')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimsintegration.invoice')),
            ],
            options={
                'db_table': 'invoice_item_old',
                'unique_together': {('invoice', 'duty')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimsintegration.crew')),
            ],
            options={
                'db_table': 'crew_invoice_old',
                'unique_together': {('crew', 'month')},
            },
        ),
    ]
