# Generated by Django 5.0.9 on 2025-07-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0007_dreammilescampaign_dreamilesemailrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableaudata',
            name='delay_number',
        ),
    ]
