# Generated by Django 5.0.9 on 2025-02-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0007_alter_tableaudata_aircraft_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableaudata',
            name='aircraft_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='aircraft_config',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='aircraft_reg_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='aircraft_type_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='arrival_station',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='delay_code_kind',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='delay_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='departure_station',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='flight_leg_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='flight_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='flight_service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tableaudata',
            name='seat_type_config',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
