# Generated by Django 5.0.9 on 2025-01-17 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0007_crewold_zoneold_airportold_dutyold_invoiceitemold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airportold',
            name='zone',
        ),
        migrations.DeleteModel(
            name='CrewOld',
        ),
        migrations.RemoveField(
            model_name='dutyold',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='dutyold',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='dutyold',
            name='departure_airport',
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitemold',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invoiceitemold',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='invoiceitemold',
            name='invoice',
        ),
        migrations.AlterUniqueTogether(
            name='invoiceold',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invoiceold',
            name='crew',
        ),
        migrations.DeleteModel(
            name='ZoneOld',
        ),
        migrations.DeleteModel(
            name='AirportOld',
        ),
        migrations.DeleteModel(
            name='DutyOld',
        ),
        migrations.DeleteModel(
            name='InvoiceItemOld',
        ),
        migrations.DeleteModel(
            name='InvoiceOld',
        ),
    ]
