# Generated by Django 5.0.9 on 2025-07-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0008_remove_tableaudata_delay_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableaudata',
            name='seat_type_config',
        ),
    ]
