# Generated by Django 5.0.9 on 2025-07-24 12:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0009_remove_tableaudata_seat_type_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewAPISMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('birth_country', models.CharField(max_length=3)),
                ('nationality', models.CharField(max_length=3)),
                ('document_type', models.CharField(choices=[('P', 'Passport')], default='P', max_length=1)),
                ('passport_number', models.CharField(db_index=True, max_length=32)),
                ('issuing_state', models.CharField(max_length=3)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField()),
                ('source_job', models.CharField(default='1008', max_length=16)),
                ('raw_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crew_apis_master',
                'indexes': [models.Index(fields=['crew_id'], name='crew_apis_m_crew_id_d63728_idx'), models.Index(fields=['passport_number'], name='crew_apis_m_passpor_393de0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job97Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message_id', models.CharField(db_index=True, max_length=128)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rec_type', models.CharField(choices=[('C', 'Crew')], default='C', max_length=1)),
                ('direction', models.CharField(choices=[('I', 'Inbound'), ('O', 'Outbound')], max_length=1)),
                ('flight_no', models.CharField(max_length=8)),
                ('dep_port', models.CharField(max_length=3)),
                ('arr_port', models.CharField(max_length=3)),
                ('dep_date', models.DateField()),
                ('dep_time', models.TimeField()),
                ('arr_date', models.DateField()),
                ('arr_time', models.TimeField()),
                ('crew_id', models.CharField(db_index=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('nationality', models.CharField(blank=True, max_length=3, null=True)),
                ('raw_line', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job97_record',
                'indexes': [models.Index(fields=['flight_no', 'dep_date', 'dep_port', 'arr_port'], name='job97_recor_flight__697fe9_idx'), models.Index(fields=['crew_id'], name='job97_recor_crew_id_e0c6d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='QatarAPISMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interchange_ref', models.CharField(db_index=True, max_length=20)),
                ('group_ref', models.CharField(max_length=20)),
                ('message_ref', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('I', 'Inbound'), ('O', 'Outbound')], max_length=1)),
                ('flight_no', models.CharField(max_length=8)),
                ('dep_port', models.CharField(max_length=3)),
                ('arr_port', models.CharField(max_length=3)),
                ('std_utc', models.DateTimeField()),
                ('sta_utc', models.DateTimeField()),
                ('persons_count', models.PositiveIntegerField()),
                ('file_path', models.CharField(max_length=512)),
                ('raw_message', models.TextField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent'), ('failed', 'Failed')], default='generated', max_length=12)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qatar_apis_message',
                'indexes': [models.Index(fields=['flight_no', 'std_utc'], name='qatar_apis__flight__0f9848_idx'), models.Index(fields=['interchange_ref'], name='qatar_apis__interch_d58eb7_idx'), models.Index(fields=['direction', 'dep_port', 'arr_port', 'std_utc'], name='qatar_apis__directi_161415_idx')],
            },
        ),
        migrations.CreateModel(
            name='QatarAPISMessagePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(db_index=True, max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=3)),
                ('document_type', models.CharField(default='P', max_length=1)),
                ('passport_number', models.CharField(max_length=32)),
                ('issuing_state', models.CharField(max_length=3)),
                ('passport_expiry_date', models.DateField()),
                ('birth_country', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='aimsintegration.qatarapismessage')),
            ],
            options={
                'db_table': 'qatar_apis_message_person',
                'indexes': [models.Index(fields=['crew_id'], name='qatar_apis__crew_id_6c4949_idx')],
            },
        ),
    ]
