# Generated by Django 5.0.9 on 2025-07-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0010_crewapismaster_job97record_qatarapismessage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrewAPISMaster',
        ),
        migrations.DeleteModel(
            name='Job97Record',
        ),
        migrations.RemoveField(
            model_name='qatarapismessageperson',
            name='message',
        ),
        migrations.DeleteModel(
            name='QatarAPISMessage',
        ),
        migrations.DeleteModel(
            name='QatarAPISMessagePerson',
        ),
    ]
