# Generated by Django 5.0.9 on 2025-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0011_delete_crewapismaster_delete_job97record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QatarApisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=6)),
                ('direction', models.CharField(choices=[('I', 'Inbound'), ('O', 'Outbound')], max_length=1)),
                ('dep_port', models.CharField(max_length=4)),
                ('dep_date', models.DateField()),
                ('dep_time', models.TimeField()),
                ('arr_port', models.CharField(max_length=4)),
                ('arr_date', models.DateField()),
                ('arr_time', models.TimeField()),
                ('crew_id', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=3)),
                ('document_type', models.CharField(default='P', max_length=10)),
                ('issuing_state', models.CharField(max_length=3)),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('country_of_birth', models.CharField(max_length=3)),
                ('document_expiry_date', models.DateField()),
                ('file_generated', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qatar_apis_record',
                'unique_together': {('flight_no', 'dep_date', 'crew_id', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='QatarCrewBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=6)),
                ('tail_no', models.CharField(blank=True, max_length=10, null=True)),
                ('flight_date', models.DateField()),
                ('origin', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=4)),
                ('crew_id', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('nationality_code', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qatar_crew_basic',
                'unique_together': {('flight_no', 'flight_date', 'origin', 'destination', 'crew_id')},
            },
        ),
        migrations.CreateModel(
            name='QatarCrewDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(max_length=20)),
                ('passport_number', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('passport_issuing_date', models.DateField(blank=True, null=True)),
                ('passport_issuing_state', models.CharField(max_length=3)),
                ('nationality_country_code', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qatar_crew_detailed',
                'unique_together': {('crew_id', 'passport_number')},
            },
        ),
    ]
