# Generated by Django 5.0.9 on 2025-07-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0012_qatarapisrecord_qatarcrewbasic_qatarcrewdetailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qatarapisrecord',
            name='country_of_birth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='qatarapisrecord',
            name='issuing_state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='qatarapisrecord',
            name='nationality',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='qatarcrewbasic',
            name='nationality_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='qatarcrewdetailed',
            name='nationality_country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='qatarcrewdetailed',
            name='passport_issuing_state',
            field=models.CharField(max_length=10),
        ),
    ]
