# Generated by Django 5.0.9 on 2025-07-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0013_alter_qatarapisrecord_country_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QatarApisRecord',
        ),
        migrations.DeleteModel(
            name='QatarCrewBasic',
        ),
        migrations.DeleteModel(
            name='QatarCrewDetailed',
        ),
    ]
