# Generated by Django 5.0.9 on 2025-07-29 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0014_delete_qatarapisrecord_delete_qatarcrewbasic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QatarCrewDetail',
            fields=[
                ('crew_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(max_length=3)),
                ('issuing_state', models.CharField(max_length=3)),
                ('place_of_issue', models.CharField(blank=True, max_length=16, null=True)),
                ('birth_place_cc', models.CharField(blank=True, max_length=3, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crew_detail',
            },
        ),
        migrations.CreateModel(
            name='QatarFlightCrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(max_length=11)),
                ('tail_no', models.CharField(blank=True, max_length=10, null=True)),
                ('dep_date_utc', models.DateField()),
                ('arr_date_utc', models.DateField(blank=True, null=True)),
                ('std_utc', models.TimeField(blank=True, null=True)),
                ('sta_utc', models.TimeField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='aimsintegration.flightdata')),
            ],
            options={
                'db_table': 'flight_crew_assignment',
                'unique_together': {('crew_id', 'flight')},
            },
        ),
    ]
