# Generated by Django 5.0.9 on 2025-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0015_qatarcrewdetail_qatarflightcrewassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qatarcrewdetail',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qatarcrewdetail',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
