# Generated by Django 5.0.9 on 2025-07-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0016_alter_qatarcrewdetail_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qatarcrewdetail',
            table='qatar_crew_detail',
        ),
        migrations.AlterModelTable(
            name='qatarflightcrewassignment',
            table='qatar_flight_crew_assignment',
        ),
    ]
