# Generated by Django 5.0.9 on 2025-07-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0017_alter_qatarcrewdetail_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qatarcrewdetail',
            name='issuing_state',
            field=models.CharField(default='RWA', max_length=3),
        ),
        migrations.AlterField(
            model_name='qatarcrewdetail',
            name='nationality',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='qatarcrewdetail',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
    ]
