# Generated by Django 5.0.9 on 2025-07-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0018_alter_qatarcrewdetail_issuing_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qatarcrewdetail',
            name='issuing_state',
        ),
        migrations.AddField(
            model_name='qatarcrewdetail',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qatarcrewdetail',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qatarflightcrewassignment',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
    ]
