# Generated by Django 5.0.9 on 2025-08-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0019_remove_qatarcrewdetail_issuing_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QatarFlightDeatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(max_length=11)),
                ('tail_no', models.CharField(blank=True, max_length=10, null=True)),
                ('dep_date_utc', models.DateField()),
                ('arr_date_utc', models.DateField(blank=True, null=True)),
                ('std_utc', models.TimeField(blank=True, null=True)),
                ('sta_utc', models.TimeField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='aimsintegration.flightdata')),
            ],
            options={
                'db_table': 'qatar_flight_details',
                'unique_together': {('crew_id', 'flight')},
            },
        ),
        migrations.DeleteModel(
            name='QatarFlightCrewAssignment',
        ),
    ]
