# Generated by Django 5.0.9 on 2025-08-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0020_qatarflightdeatails_delete_qatarflightcrewassignment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QatarFlightDeatails',
            new_name='QatarFlightDetails',
        ),
    ]
