# Generated by Django 5.0.9 on 2025-08-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0021_rename_qatarflightdeatails_qatarflightdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='qatarcrewdetail',
            name='nationality_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
