# Generated by Django 5.0.9 on 2025-09-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0022_qatarcrewdetail_nationality_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableaudata',
            name='actual_block_time_mvt',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tableaudata',
            name='flight_time_mvt',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
