# Generated by Django 5.0.9 on 2025-10-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0023_tableaudata_actual_block_time_mvt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableaudata',
            name='actual_block_time_mvt',
        ),
        migrations.RemoveField(
            model_name='tableaudata',
            name='flight_time_mvt',
        ),
    ]
