# Generated by Django 5.0.9 on 2025-10-22 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0024_remove_tableaudata_actual_block_time_mvt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qatarflightdetails',
            name='apis_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qatarflightdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 22, 14, 29, 57, 407098, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qatarflightdetails',
            name='direction',
            field=models.CharField(blank=True, choices=[('I', 'Inbound'), ('O', 'Outbound')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='qatarflightdetails',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent'), ('PROCESSED', 'Processed'), ('RECEIVED', 'Received')], db_index=True, default='GENERATED', max_length=20),
        ),
        migrations.AddField(
            model_name='qatarflightdetails',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qatarflightdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='qatarflightdetails',
            index=models.Index(fields=['status', 'dep_date_utc'], name='qatar_fligh_status_ff6515_idx'),
        ),
        migrations.AddIndex(
            model_name='qatarflightdetails',
            index=models.Index(fields=['direction', 'dep_date_utc'], name='qatar_fligh_directi_58a159_idx'),
        ),
    ]
