# Generated by Django 5.0.9 on 2025-11-03 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0025_qatarflightdetails_apis_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeppessenProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=255)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_lines', models.IntegerField(default=0)),
                ('successful_lines', models.IntegerField(default=0)),
                ('failed_lines', models.IntegerField(default=0)),
                ('total_flights', models.IntegerField(default=0)),
                ('total_crew', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_duration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jeppesen_processing_log',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='JeppessenFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(db_index=True, max_length=6)),
                ('flight_date', models.DateField(db_index=True)),
                ('origin_iata', models.CharField(max_length=3)),
                ('origin_icao', models.CharField(blank=True, max_length=4, null=True)),
                ('destination_iata', models.CharField(max_length=3)),
                ('destination_icao', models.CharField(blank=True, max_length=4, null=True)),
                ('raw_line', models.TextField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jeppesen_flight',
                'ordering': ['-flight_date', 'flight_no'],
                'indexes': [models.Index(fields=['flight_no', 'flight_date'], name='jeppesen_fl_flight__dcedb8_idx'), models.Index(fields=['flight_date'], name='jeppesen_fl_flight__d5320e_idx')],
                'unique_together': {('flight_no', 'flight_date', 'origin_iata', 'destination_iata')},
            },
        ),
        migrations.CreateModel(
            name='JeppessenCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(db_index=True, max_length=6)),
                ('flight_date', models.DateField(db_index=True)),
                ('origin', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=4)),
                ('crew_id', models.CharField(max_length=4)),
                ('full_crew_id', models.CharField(blank=True, max_length=10, null=True)),
                ('crew_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('CP', 'Captain'), ('FO', 'First Officer'), ('FP', 'Purser'), ('SA', 'Senior Attendant'), ('FA', 'Flight Attendant'), ('FE', 'Flight Engineer'), ('MX', 'Maintenance'), ('AC', 'Air Crew')], max_length=2)),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='aimsintegration.jeppessenflight')),
            ],
            options={
                'db_table': 'jeppesen_crew',
                'ordering': ['-flight_date', 'flight_no', 'position'],
                'indexes': [models.Index(fields=['flight_no', 'flight_date'], name='jeppesen_cr_flight__1ff57e_idx'), models.Index(fields=['crew_id'], name='jeppesen_cr_crew_id_47ddfd_idx'), models.Index(fields=['flight_date'], name='jeppesen_cr_flight__5c7491_idx'), models.Index(fields=['position'], name='jeppesen_cr_positio_d22aaf_idx')],
                'unique_together': {('flight_no', 'flight_date', 'origin', 'destination', 'crew_id')},
            },
        ),
    ]
