# Generated by Django 5.0.9 on 2025-11-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0026_jeppessenprocessinglog_jeppessenflight_jeppessencrew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('backup_type', models.CharField(default='daily', max_length=50)),
                ('backup_date', models.DateField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=50)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
