# Generated by Django 5.0.9 on 2025-11-14 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0026_jeppessenprocessinglog_jeppessenflight_jeppessencrew'),
    ]

    operations = [
        migrations.CreateModel(
            name='JEPPESSENGDCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(db_index=True, max_length=11)),
                ('position', models.CharField(choices=[('CP', 'Captain'), ('FO', 'First Officer'), ('FP', 'Purser'), ('SA', 'Senior Attendant'), ('FA', 'Flight Attendant'), ('FE', 'Flight Engineer'), ('MX', 'Maintenance'), ('AC', 'Air Crew'), ('PIC', 'Pilot in Command'), ('SIC', 'Second in Command')], max_length=3)),
                ('role', models.CharField(blank=True, max_length=3, null=True)),
                ('is_pic', models.BooleanField(db_index=True, default=False)),
                ('is_sic', models.BooleanField(db_index=True, default=False)),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('flight_no', models.CharField(db_index=True, max_length=6)),
                ('flight_date', models.DateField(db_index=True)),
                ('origin', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=4)),
                ('tail_no', models.CharField(blank=True, max_length=10, null=True)),
                ('dep_date_utc', models.DateField(blank=True, null=True)),
                ('arr_date_utc', models.DateField(blank=True, null=True)),
                ('std_utc', models.TimeField(blank=True, null=True)),
                ('sta_utc', models.TimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gd_crew_assignments', to='aimsintegration.flightdata')),
            ],
            options={
                'db_table': 'jeppessen_gd_crew',
                'ordering': ['-flight_date', 'flight_no', '-is_pic', '-is_sic', 'position'],
            },
        ),
        migrations.CreateModel(
            name='JEPPESSENGDCrewDetail',
            fields=[
                ('crew_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True)),
                ('nationality_code', models.CharField(blank=True, max_length=3, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('last_seen_flight_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jeppessen_gd_crew_detail',
            },
        ),
        migrations.CreateModel(
            name='JEPPESSENGDFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(db_index=True, max_length=6)),
                ('flight_date', models.DateField(db_index=True)),
                ('origin_iata', models.CharField(max_length=3)),
                ('origin_icao', models.CharField(blank=True, max_length=4, null=True)),
                ('destination_iata', models.CharField(max_length=3)),
                ('destination_icao', models.CharField(blank=True, max_length=4, null=True)),
                ('tail_no', models.CharField(blank=True, max_length=10, null=True)),
                ('std_utc', models.TimeField(blank=True, null=True)),
                ('sta_utc', models.TimeField(blank=True, null=True)),
                ('raw_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_declarations', to='aimsintegration.flightdata')),
            ],
            options={
                'db_table': 'jeppessen_gd_flight',
                'ordering': ['-flight_date', 'flight_no'],
            },
        ),
        migrations.CreateModel(
            name='JEPPESSENGDProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=255)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gd_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('total_crew', models.IntegerField(default=0)),
                ('emails_found', models.IntegerField(default=0)),
                ('emails_not_found', models.IntegerField(default=0)),
                ('pic_identified', models.BooleanField(default=False)),
                ('sic_identified', models.BooleanField(default=False)),
                ('flight_found', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_duration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jeppessen_gd_processing_log',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='jeppessencrew',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jeppessencrew',
            name='flight',
        ),
        migrations.AlterUniqueTogether(
            name='jeppessenflight',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='JeppessenProcessingLog',
        ),
        migrations.AddField(
            model_name='jeppessengdcrew',
            name='gd_flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='aimsintegration.jeppessengdflight'),
        ),
        migrations.DeleteModel(
            name='JeppessenCrew',
        ),
        migrations.DeleteModel(
            name='JeppessenFlight',
        ),
        migrations.AddIndex(
            model_name='jeppessengdflight',
            index=models.Index(fields=['flight_no', 'flight_date'], name='jeppessen_g_flight__63c014_idx'),
        ),
        migrations.AddIndex(
            model_name='jeppessengdflight',
            index=models.Index(fields=['flight_date'], name='jeppessen_g_flight__2167e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jeppessengdflight',
            unique_together={('flight_no', 'flight_date', 'origin_iata', 'destination_iata')},
        ),
        migrations.AddIndex(
            model_name='jeppessengdcrew',
            index=models.Index(fields=['crew_id', 'flight_date'], name='jeppessen_g_crew_id_e3e751_idx'),
        ),
        migrations.AddIndex(
            model_name='jeppessengdcrew',
            index=models.Index(fields=['flight_date', 'is_pic'], name='jeppessen_g_flight__cdf157_idx'),
        ),
        migrations.AddIndex(
            model_name='jeppessengdcrew',
            index=models.Index(fields=['flight_date', 'is_sic'], name='jeppessen_g_flight__d3e258_idx'),
        ),
        migrations.AddIndex(
            model_name='jeppessengdcrew',
            index=models.Index(fields=['position'], name='jeppessen_g_positio_4e987b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jeppessengdcrew',
            unique_together={('crew_id', 'gd_flight')},
        ),
    ]
