# Generated by Django 5.0.9 on 2025-11-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0027_backup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ['-backup_date']},
        ),
        migrations.AddField(
            model_name='backup',
            name='backup_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='backup',
            table='backup',
        ),
    ]
