# Generated by Django 5.0.9 on 2025-11-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0027_jeppessengdcrew_jeppessengdcrewdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlitelinkAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('SUBMIT', 'Submit Flight'), ('STATUS', 'Check Status')], max_length=20)),
                ('request_id', models.UUIDField(db_index=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('http_method', models.CharField(max_length=10)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flitelink_api_log',
                'ordering': ['-request_time'],
            },
        ),
        migrations.AddField(
            model_name='jeppessengdflight',
            name='flitelink_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jeppessengdflight',
            name='flitelink_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jeppessengdflight',
            name='flitelink_last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jeppessengdflight',
            name='flitelink_request_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jeppessengdflight',
            name='flitelink_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jeppessengdflight',
            name='flitelink_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jeppessengdflight',
            name='flitelink_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='NOT_SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='jeppessengdflight',
            name='flitelink_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='jeppessengdflight',
            index=models.Index(fields=['flitelink_status'], name='jeppessen_g_fliteli_6e82a6_idx'),
        ),
        migrations.AddIndex(
            model_name='jeppessengdflight',
            index=models.Index(fields=['flitelink_request_id'], name='jeppessen_g_fliteli_5f2d73_idx'),
        ),
        migrations.AddField(
            model_name='flitelinkapilog',
            name='gd_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flitelink_api_logs', to='aimsintegration.jeppessengdflight'),
        ),
        migrations.AddIndex(
            model_name='flitelinkapilog',
            index=models.Index(fields=['request_id', '-request_time'], name='flitelink_a_request_f12653_idx'),
        ),
        migrations.AddIndex(
            model_name='flitelinkapilog',
            index=models.Index(fields=['gd_flight', '-request_time'], name='flitelink_a_gd_flig_6d95ec_idx'),
        ),
    ]
