# Generated by Django 5.0.9 on 2025-11-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0028_alter_backup_options_backup_backup_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewDocumentsArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_number', models.IntegerField()),
                ('crew_name', models.CharField(max_length=255)),
                ('date_of_leaving', models.DateField(auto_now_add=True)),
                ('position', models.CharField(max_length=255)),
                ('archive_date', models.DateField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crew_documents_archive',
                'ordering': ['-date_of_leaving'],
            },
        ),
    ]
