# Generated by Django 5.0.9 on 2025-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0029_crewdocumentsarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewdocumentsarchive',
            name='wb_number',
            field=models.IntegerField(unique=True),
        ),
    ]
