# Generated by Django 5.0.9 on 2025-11-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0030_alter_crewdocumentsarchive_wb_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewdocumentsarchive',
            name='archive_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='crewdocumentsarchive',
            name='date_of_leaving',
            field=models.DateField(),
        ),
    ]
