# Generated by Django 5.0.9 on 2025-12-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0031_alter_crewdocumentsarchive_archive_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewdocumentsarchive',
            name='archive_path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='backup_type',
            field=models.CharField(default='weekly', max_length=50),
        ),
    ]
