# Generated by Django 5.0.9 on 2025-12-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimsintegration', '0028_flitelinkapilog_and_more'),
        ('aimsintegration', '0032_crewdocumentsarchive_archive_path_and_more'),
    ]

    operations = [
    ]
