# Generated by Django 5.0.9 on 2025-01-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
    ]
