# Generated by Django 5.0.9 on 2024-10-24 10:28

import authentications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=authentications.models.get_staff_role, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentications.role'),
        ),
    ]
